### ISSUE TITLE
Lowered friendship requirement from the new randomizer setting is not reflected on Tracker

### ISSUE THREAD

**Issue by UTDZac** [besteon/Ironmon-Tracker#128]
**Version**: v0.5.3

The Tracker currently informs the user if their lead Pokemon is ready to evolve. This is especially helpful for friendship evolutions where the Tracker knows the Pokemon's current friendship value. In the base game, different Pokemon may have different starting base friendship values (normally 70), but they all evolve at friendship value of 220.

As of Randomizer ZX 4.5.1 there exists a setting to speed up friendship evolutions. Unfortunately for us, this setting changes the value required for evolving (160 instead of 220) instead of the base friendship value when caught. Therefore, if the user is playing on a ROM with this adjusted setting and they get their Pokemon to the required friendship value (160), the Tracker still won't show it as ready to evolve, since it looks for the original value of 220.

Source: https://github.com/Ajarmar/universal-pokemon-randomizer-zx/issues/485#issuecomment-1185646762

I'm not sure where this required friendship value for evolving would be, and expect it to be different for other friendship related things like Return and Frustration.

**Comment by Fellshadow** [comment]
Did a little bit of digging and the friendship value the game checks is hardcoded instead of being stored in the evolutionTable params like other evo methods (same thing in all three games, though FRLG specifically don't use day/night friendship evos), which means we'd need to search for it in the ROM data, and i'm not sure what the offset/address darkeye used for the randomiser setting is

https://github.com/pret/pokeruby/blob/master/src/pokemon_3.c#L295
https://github.com/pret/pokefirered/blob/master/src/pokemon.c#L4940
https://github.com/pret/pokeemerald/blob/master/src/pokemon.c#L5479

This is indeed separate from return and frustration calculations to note, so don't need to worry about those

**Comment by UTDZac** [comment]
Found it. `08042ed8 g 000002f0 GetEvolutionTargetSpecies` is the function where the hardcoded value exists. The Randomizer changes the value here from `219` (not 220) to `159`. So doing some quick memory digging, I found this lives at that address with the offset of 318, or 0x13E.

So in short, this will return the friendship value needed to evolve via happiness:
```Memory.readbyte(GameSettings.GetEvolutionTargetSpecies + 0x13E)```
