### ISSUE TITLE
QoL Improvements

### ISSUE THREAD

**Issue by Tapollo** [besteon/Ironmon-Tracker#16]
- Add current Status Effect
- Add whether a move is Physical or Special

**Comment by bdjeffyp** [comment]
I don't believe that adding status effect is necessary in the limited space we have, since that is shown in battle. When outside of battle, the effect of status effects that can kill your Pokémon is apparent as you take steps.
My personal thought is that we should support the Special/Physical/Neutral icons for moves in the future since this will be more important if we grow support out to later generations. However, BizHawk support for systems beyond the GBA is limited at the moment and so I believe that this should be lower priority. Move types are fairly easy to remember for Gen 3 and below because of the "Eeveelutions + Dragon" rule.

**Comment by bdjeffyp** [comment]
In discussions with besteon, I will be working on implementing the Physical/Special/Status attack icons for the moves list and getting it working in Gen 3, which will prepare us for future gens anyway. So look forward to see that soon-ish!
