### ISSUE TITLE
[Move] Focus Punch doesn't track on "warmup"

### ISSUE THREAD

**Issue by besteon** [besteon/Ironmon-Tracker#18]
This may apply to all 2 turn moves. The move is not tracked during the first turn of the move.

**Comment by Fellshadow** [comment]
Just to update on the current situation with this issue

As of tracker v0.5.0 2-turn moves do get tracked during their charging turn, as the trigger for tracking a move is now checking if current pp is less than the move's max. Don't know/remember if they weren't being tracked during the charging turn before.

Focus punch however does not lose pp until it actually goes off at the end of the turn, so we'd need to have some workaround to tell when the charging animation of focus punch goes off in order to track it properly

**Comment by UTDZac** [comment]
**Config for reproducing this issue**
Game: FireRed v1.0
Random Seed: 41564108002595
Settings String: 320WRIEEjIBAAQABwCRAAKeBnsEiAEAFAACCQAuEgAAAAAABRi45ATkAYYICTIGBAIyEwUAEEZpcmUgUmVkIChVKSAxLjCmGjJx+xZz7w==

Ledyba has Focus Punch in this seed and is one of the starters

**Comment by UTDZac** [comment]
Reopening because the current solution fails under some conditions:

- If both you and opponent have the move Focus Punch,, and...
- you use Focus Punch, they do not, and...
- the punch message appears, but you check if opponent has the punch move (true), therefore it gets tracked incorrectly (they never used it).
