### ISSUE TITLE
Route Info: The MORE button shouldn't be visible when there are no other encounter tables

### ISSUE THREAD

**Issue by UTDZac** [besteon/Ironmon-Tracker#182]
Version: 0.6.1

Currently the More button is displayed on the Route Info page at all times, even for zones that only have a single encounter table. This can potentially be confusing as the button exists but nothing happens when it is pressed.

Ideally this button should be hidden if no other encounter table is visible. This might not be an easy fix, as we eventually want Trainer encounter tables added in. So we'd need a way to properly distinguish this, or consider how a user would want to use this information.

![image](https://user-images.githubusercontent.com/4258818/184551214-df8caf82-3921-4aa2-99b5-cd2ec17e4fa7.png)

**Comment by Fellshadow** [comment]
I wonder if there'd be enough space to implement back/forward buttons like this to cycle between encounter pages, which would be much clearer imo for the intended purpose. These wouldn't necessarily need to be removed if there aren't more pages to view due to being clearer that it's to cycle encounter types but of course would still be cleanest/ideal to do so
Idea mockup:
![Screenshot_20](https://user-images.githubusercontent.com/106463662/184627082-9d945e23-364a-433b-8a72-39f3df9971d8.png)
