### ISSUE TITLE
Ability Info Screen: User should be able to click on abilities to see information about them

### ISSUE THREAD

**Issue by UTDZac** [besteon/Ironmon-Tracker#183]
Version: 0.6.1

This is a new feature request to allow users to be able to click on the Ability text area to see an Info Screen (similar to Move data) to learn more about how the ability works. This is a great feature for users who are less experienced with Pokemon games, or want a reminder about the specifics of a certain ability.

With this change, the current functionality of clicking on an ability to manually change what ability is tracked for an enemy Pokémon needs to be changed. I suggest moving the contents of that form to the Notes form and preserving the functionality of being able to manually set the abilities. Typically this manual tracking won't be necessary because of the improvements to auto-ability tracking added in 0.6.0.

![image](https://user-images.githubusercontent.com/4258818/184551307-fd2a97ed-242a-4cec-8bff-821d8f461609.png)

**Comment by UTDZac** [comment]
A potentially accurate source for ability data and any bonuses they might have:
https://strategywiki.org/wiki/Pok%C3%A9mon_FireRed_and_LeafGreen/Abilities

**Comment by jtigues** [comment]
Starting to look into this. A few points:
http://www.psypokes.com/emerald/abilities.php
- Looks like there's one other, Magma Armor, which also does the reduced egg hatching cycles. Bulba shows it as well
- I like moving abilities to the notes popup, especially now that the notes are visible from the info screen; you can go in and mark any pokemon's ability whenever which is something even I find myself wishing for.
- I imagine that, especially since those out-of-battle Emerald-only secondary effects are not mentioned, that we'll want to put together a data file similar to MoveData which has the descriptions. We also have a list of abilities in MiscData and in all of the foreign language translation files. Would probably be cleaner to consolidate that list into this new file and expand on that instead of having 2 lists.
