### ISSUE TITLE
Encounter data fails sometimes when a new game starts

### ISSUE THREAD

**Issue by UTDZac** [besteon/Ironmon-Tracker#186]
Version: 0.6.1

Under some rare conditions that have to do with restarting the current ROM with Bizhawk, the old tracker data from the previous run will be loaded into the new run. This is problematic because as a new game begins the Trainer ID of the player will change. The Trainer ID is used to determine if an encounter with a Pokémon is a wild encounter ("Trainer ID" of the wild matches the user) or a battle with a trainer (mismatched IDs).

The current code determines the Trainer ID of the player simply by waiting until they receive their first Pokemon, then setting the Trainer ID in `Tracker.Data` to that value.

Note: All wild Pokémon have a Trainer ID that matches the player. All gift Pokémon and Pokémon belonging to an enemy trainer have a different Trainer ID.

![image](https://user-images.githubusercontent.com/4258818/184552105-02aecbdc-d9d5-43ce-a2c5-58564ea51941.png)

**References:**
- Trainer ID read in from here <https://github.com/mkdasher/PokemonBizhawkLua/blob/aef8c355bb0e0c69f00f5edb656722787c97f5e0/pkmgen3/Program.lua#L77>
- and here <https://github.com/mkdasher/PokemonBizhawkLua/blob/aef8c355bb0e0c69f00f5edb656722787c97f5e0/pkmgen3/GameSettings.lua#L44>

**Known Issues/Blocks:**
- Implementing this fix seems particularly challenging if we want to do it in such a way as to not repeatedly read in the Trainer ID from memory all the time. Ideally the ID is read in exactly once and doesn't have to be read from memory again. However, I don't know how to *know* for certain the ID that is currently stored in Tracked Data is accurate to the current game or if its the wrong ID and needs to be read in again.

**Comment by jtigues** [comment]
So the scenario here is: I have file FireRed44.gba open for example. I start a new game in the current file, meanwhile it has all my old data from before I started the new game? And the issue arises specifically when you get into encounters?

The trouble is, you want to be able to tell that something in memory which can change at any time has changed. There's not really a way to do that without reading _something_ from memory constantly. If not the trainer ID directly, then whether the user has 0 pokemon, or whether they're in the 'Lab fight'.

Maybe there's some New Game flag that gets set only when you start a new game, and you could memory write event to nil the trainer ID when it gets flipped. But I'm not sure that a memory write event isn't as intensive as just a script that constantly reads that same memory and checks for the change ourselves

**Comment by UTDZac** [comment]
One thing to consider is looking for a solution that isn't necessarily reading the TrainerID from game memory at all times. Obviously that wouldn't be ideal and runs into some issues as you've pointed out.

For example, another possible solution is to somehow verify that a different game has been loaded to erase the Tracker's tracked data. Or instead of just doing this automatically (sounds scary), we can notify the user on the Tracker Screen that old data has been loaded, therefore they can make the judgment call on how to handle it.

**Comment by Fellshadow** [comment]
Just noting that we already have the pointer for [trainer id](https://github.com/pret/pokefirered/blob/b3c2c7291fce8e427ed589d4706a75e9ca24735b/include/global.h#L319), it gets stored in `gSaveBlock2` and we already have `gSaveBlock2Ptr` in our gamesettings (though would want to add `gSaveBlock2` for RS if using this). PokemonBizhawkLua is just using this pointer, but calling it "trainerPointer" (though not sure what the addresses they put down for RS are, since they don't use pointers?)

Trainer ID gets initialised in [`InitPlayerTrainerId`](https://github.com/pret/pokefirered/blob/b3c2c7291fce8e427ed589d4706a75e9ca24735b/src/new_game.c#L54) from `new_game.c` which gets called by [`NewGameInitData`](https://github.com/pret/pokefirered/blob/b3c2c7291fce8e427ed589d4706a75e9ca24735b/src/new_game.c#L107) in the same file. This function is called by [`CB2_NewGame`](https://github.com/pret/pokefirered/blob/b3c2c7291fce8e427ed589d4706a75e9ca24735b/src/overworld.c#L1513) from overworld.c which is called at the end of the professor's dialogue in the intro cutscene (this is also where the pc potion generation happens btw). RSE have similar functions, just RS don't use a pointer

Did some memory reads of the trainer id in saveblock2 and interestingly in both FRLG and Emerald it consistently gets set to 59904 briefly before becoming 0 on initially loading the game though i don't know why lol but this happens in a short enough time that we could probably avoid it by putting the read in the set of reads that occur every half-second or maybe even every 3 seconds like badges, which would probably be plenty of time to get a non-zero read before old tracker data could interfere in gameplay

There's also a `gTrainerId` (`sTrainerId` in Emerald) which seems to store the trainer id as soon as you enter the name character screen, but also sometimes takes a random value on the title screen?

**Comment by Fellshadow** [comment]
Alternatively, if we want to reset the tracker data automatically, there's a [`gDifferentSaveFile`](https://github.com/pret/pokefirered/blob/b7a624077caceaccb9159140c5d6cd4db8c3a792/src/new_game.c#L112) address which gets set to 1 in RS, TRUE in FRLG/Emerald in the `NewGameInitData` function which we could use as a flag to reset the data

**Comment by jtigues** [comment]
Mentioned in the discord as well but moving the thoughts here as well:
Zac made a good point that some folks go on to the next seed in weird ways. Someone might be generating their 100 seeds numbered 1-100, and then when they're done, clearing the seeds and generating the same numbered seeds over again.
So the same seed number becomes a 'New' game without actually going through the new game process.

I was thinking that we could create an isNewGame flag, and in the part of the code that loops through our pokemon team in memory looking for data, set it to 'true' if no valid pokemon are found i.e. until Oak/Birch gives you your first pokemon. I recall there being a method of save state copying which allows users to start in the lab with their pokemon already chosen though which would bypass that, so maybe instead we'd need to hook into that first battle of the game. I haven't looked at RSE much to know if the Birch fight has similar/the same flags set.

Are there any other ways that folks are making new games that would bypass the actual new game popup though? Using a save state for a same-named file is the only scenario I could think of.

**Comment by UTDZac** [comment]
I have not have the time yet to investigate this to the point where I can reproduce it. Most of this has been me seeing that others are struggling, and run into the issue. So it's a bit challenging to determine how exactly they end up in this situation, and what they are doing to their rom(s).

If I had to guess, this is what's going on, but would have to test it later, just swamped atm.

1. Open Bizhawk and load a randomized ROM: `FireRed1.gba`
2. Play for a few minutes, enough to encounter a wild Pokemon
3. During battle (your pokemon has died, rip), keep ROM open and Bizhawk running.
4. Open the Randomizer ZX program, load a vanilla rom, load settings, and hit "Randomize (Save)"
5. Overwrite the old rom: `FireRed1.gba`
6. Restart the game (which I think is Reboot Core?)
7. Check if old tracked data is loaded

**Comment by UTDZac** [comment]
I'm still not sold on the absolute perfect solution yet. Notably, a solution to ensure that no matter what a player does, when they begin a new game it should reset the tracked data. This has to be full proof, and it cannot risk erasing data of a real run due to user error.

**Comment by Fellshadow** [comment]
> I recall there being a method of save state copying which allows users to start in the lab with their pokemon already chosen though which would bypass that, so maybe instead we'd need to hook into that first battle of the game

The savestate can't be after getting the pokemon i'm pretty sure, because if you load up that savestate on a different rom it just gives you the pokemon you had when you made the savestate because of weird memory shenanigans with how savestates work. The savestate trick at latest has to be just before the starter choice for different roms to prevent weird stuff happening (the only downside would usually be not having the pc potion be randomised if savestating after starting in the room)

**Comment by Fellshadow** [comment]
> I have not have the time yet to investigate this to the point where I can reproduce it. Most of this has been me seeing that others are struggling, and run into the issue. So it's a bit challenging to determine how exactly they end up in this situation, and what they are doing to their rom(s).
> 
> If I had to guess, this is what's going on, but would have to test it later, just swamped atm.
> 
>     1. Open Bizhawk and load a randomized ROM: `FireRed1.gba`
> 
>     2. Play for a few minutes, enough to encounter a wild Pokemon
> 
>     3. During battle (your pokemon has died, rip), keep ROM open and Bizhawk running.
> 
>     4. Open the Randomizer ZX program, load a vanilla rom, load settings, and hit "Randomize (Save)"
> 
>     5. Overwrite the old rom: `FireRed1.gba`
> 
>     6. Restart the game (which I think is Reboot Core?)
> 
>     7. Check if old tracked data is loaded

I couldn't reproduce following these steps or by using file -> open rom to reopen the current rom on step 6 instead, with each randomisation the rom hash changes (at least it did for me) so the tracker considered it a new rom.

>  Someone might be generating their 100 seeds numbered 1-100, and then when they're done, clearing the seeds and generating the same numbered seeds over again.
So the same seed number becomes a 'New' game without actually going through the new game process.

In this scenario each of those roms should also have different rom hashes so should reset tracker data between each of the seeds anyway. Even if the old seed 1 were the same rom hash as the new seed 1 the tracker data would have been reset on loading seed 2 anyways i think

Given the above, not really sure at all in what scenario the rom hash is the same other than just reloading the same rom without re-randomising, it's a tricky one, but rom hash staying the same is ultimately why old tracker data gets loaded in.

**Comment by UTDZac** [comment]
Re-posting this discussion from the discord here for completeness. I think this might actually do what we want to solve the big part of this issue, where encounters are shown incorrectly

> quick thought on the encounter issue we've been chatting about with regards to trainer id. What do you think of this solution:
> 
> During the Battle.checkEnemyEncounter(), if the Pokemon hasnt been encountered yet (We have this logic already), we read in the TrainerID from the saveblock. This is the most-accurate trainer ID possible. Then we use this value to compare to the encountered pokemon to see if its a wild/trainer fight. This way no matter what happens with the tracked data, its always accurate.
> 
> This solves any issue with old/corrupted tracked data interfering with encountering a "trainer" as a wild or whatever. This solves only half of the core issue, but it solves the important half that breaks tracker functionality

**Comment by UTDZac** [comment]
This should likely be fixed with Fellshadow's trainer ID check. Closing this issue for now, but if it resurfaces I'll revive this thread.
