### ISSUE TITLE
Pokemon info is revealed when it shouldn't be while learning a move immediately after evolving

### ISSUE THREAD

**Issue by UTDZac** [besteon/Ironmon-Tracker#201]
Version: 0.6.0

When a Pokemon evolves and then immediately learns a move, the Tracker reveals the new stat information about your evolved Pokemon. These stats and abilities are information that the user cannot normally know because they are stuck in the Learning a Move prompt. So they can't check the summary of the evolved Pokemon.

I suppose one solution here is to hide the info in a similar way as we do when hiding for mustCheckSummary.

![image](https://user-images.githubusercontent.com/4258818/185764771-380552bf-2a01-46e7-b198-1ff6bacd26ff.png)

**Comment by UTDZac** [comment]
Labeling this as a bug because this breaks the first rule of the Tracker: don't show information to the player that they couldn't otherwise have themselves.

**Comment by jtigues** [comment]
Dumping everything here so some other poor soul doesn't also dive into this. The bad news:

- FRLG and E have a flag specifically when evolution triggers. RS has no such flag.
- There is a return pointer set in all games when an evolution takes place, which tells the game where to return in battle. This does not get set, though, for evos that occur outside of battle aka from items

The good news:
- Each game has a data structure which governs evolution data (sEvoInfo in RS, sEvoStructPtr in FRLG/E), and a list of tasks (gTasks), of which evolution has several.
- The evolution task can be looked up and has a variable dedicated to the function (which can be tied back to an evolution task), and a state (evolution ends on 15, otherwise it is playing an animation or learning a move), as well as some other useful things.

Working on setting it up so that if the evolution task is active, we only update the tracker if the Task is on the final state

**Comment by jtigues** [comment]
https://user-images.githubusercontent.com/12836386/186820858-4b5ecb91-2a15-4e69-9480-9920e8b5a026.mp4

Working for RS, checking FRLG

**Comment by UTDZac** [comment]
Resolved as of #216 and #220
