### ISSUE TITLE
Error while generating new rom

### ISSUE THREAD

**Issue by depsir** [besteon/Ironmon-Tracker#215]
I'm experiencing an issue with release 0.6.2 and bizhawk 2.8 win x64
Not sure whether this is about the tracker or bizhawk though.

When I generate a new rom with the new quick-load setting, I see an alert with the error in the screenshot below.
The lua script is set to auto reload but removing it does not solve the issue.
If I close the popup, everything works fine: the tracker is loaded and the rom is a newly generated one

![2022-08-25 (2)](https://user-images.githubusercontent.com/631731/186771089-8e9185db-4749-435d-aaf7-545b9a9de6ed.png)

**Comment by Fellshadow** [comment]
Hmm ok, do you have a savestate set to autoload with the rom? If so then try disabling the autoload savestate option

In the past that's caused issues for some people as the savestate would load before the tracker finishes loading on a new seed so it winds up attempting to start a second instance of the tracker

**Comment by depsir** [comment]
Hi, disabling savestate autoload the issue disappears.
I'm not sure though it is a bizhawk bug only: my previous workflow for starting a new randomized rom would be

1. generate a new randomized rom with the same name of the previous one (batch file which executed java -jar PokeRandoXz.jar cli .....)
2. ctrl + r to reload the rom (with auto load state enabled)

I guess the randomizer is doing the same for step 1, but something different for step 2, which leads to the error

**Comment by Fellshadow** [comment]
Ah ok that's interesting, it's bizhawk-related in some way as i think the savestate autoloading is causing the tracker to restart/reload while the previous instance from reopening the rom is still loading things (so can't shut down fully)

Interesting that rebooting the core with ctrl+r didn't cause that issue for you, i'd do some testing on this but not at home at the moment so can't for another couple of days. Thanks for mentioning this though

**Comment by depsir** [comment]
I did some testing looking for a workaround and here is what I found out.

First test was to substitute `client.openrom` with `client.reboot_core()` but somehow the problem was still there. I guess that there is something wrong with the lua api with auto load states (bizhawk only, but should be tested further to be confirmed)

Second test was to disable bizhawk autoload and load the save "manually" from the script with `savestate.loadslot(1)` just after opening the new rom. Still nothing (which means I was loading the slot too early).

Then I moved the slot loading in the `Main.Run` function after the `romLoaded` check loop and this solved the issue.


One thing that could be done as a workaround, if you like it, would be to add a new setting for the quick load feature where someone can specify a "saved state file name to start kaizo runs"
If the setting is present and the Main.Run knows is being called after a quick load (should be doable with a parameter or something) it could load the state for the user.
Still some drawbacks, needs some thinking but may go in the right direction.

Also.. am I the only one having this issue? Because maybe the workaround is not worth doing...


p.s. I made another small improvement: disabling the sound a bit earlier, before generating the new rom, which for me freezed the audio for one second. Didn't want to add another issue for this one but it might be useful

**Comment by UTDZac** [comment]
Hey @depsir thank you for the research around this issue. You are not the first to encounter it, but it's also not very common or reported often. A few of my thoughts here:

- Having an option to specify a save state to load up when you quick-load could be possible, but also a bit tricky. Mostly because there simply isn't enough room on the quick-load setup page at the moment. It's also something that is more of an emulator thing that very few people use. Those who want to skip stuff with a save state tend to just bind that save state to a hotkey on their emulator, then press that button after a new game begins. I'm not saying I'm completely against adding this feature to the Tracker, it's more that I don't think there are that many people who could benefit from it. Most people simply use intro skip patches, or they like going through the beginning stuff, or they already have a process to manually tap a button to load the next save state.
- Regarding your P.S. sound fix, that's great to hear. This was actually reported earlier this morning. I've made this fix as well as part of https://github.com/besteon/Ironmon-Tracker/commit/5143f83c08d5f3bd4d61dd6c14a88d6009bc7d87 and this fixed version is available for download now on the release page (same download link).

**Comment by UTDZac** [comment]
Trying to determine if this is at all solvable in the sense of allowing the Bizhawk Auto-load save state feature. I can't quite see how it can be done because the current script that is used to open the next ROM has to finish out (at a minimum, turn the sound back on).

There also does not appear to be a Bizhawk supported way to disable the auto-load save state feature, then turn it back on or manually load that save state from a path, somehow.

However, it does seem that an adequate workaround is: Disable Bizhawk's auto-load feature for save states and instead assign a hotkey to manually load a save state.

**Comment by UTDZac** [comment]
Closing this one for the time being. If there is more demand to have compatibility for the Tracker to handle auto-loading of save states, then this would be a worthwhile threat to revisit for implementing support for such a feature. For now, the workaround of simply disabling auto-load and using a hotkey is sufficient.
