### ISSUE TITLE
Track when enemy has Pressure

### ISSUE THREAD

**Issue by AleshaDevitt** [besteon/Ironmon-Tracker#247]
The tracker automatically tracks abilities when you receive information that lets you know they have them. Currently, however, this is not the case for Pressure, even though you are able to see that your PP goes down by 2.

**Comment by Fellshadow** [comment]
This is by choice. Abilities get auto-tracked when:
- Their effect goes off (corresponding to an in-game message saying the ability was used)
- The player sends out a pokemon in battle, in this case the player pokemon's ability gets tracked for that pokemon since the player knows it.
   - In battle was chosen to avoid tracking info in catch & release scenarios.
- The player pokemon traces the enemy's ability (which pops up with a message stating that ability)

We discussed whether to track Pressure from pp usage when doing the ability auto-tracking and the conclusion was that we shouldn't reveal it since it's not revealed in-game (Pressure in gen 3 does *not* ever have a message showing that it's in effect). Similarly, we avoid tracking abilities in cases like skill swap since the game doesn't tell you what ability you got given in gen 3.

Figuring out it has Pressure from the pp drop shown in the tracker is the same as you would conclude yourself from what you see in-game, with the knowledge of what Pressure does. You can then use the notes feature to manually track that it has Pressure.
