### ISSUE TITLE
Provide resistances and immunity information when viewing a Pokemon

### ISSUE THREAD

**Issue by UTDZac** [besteon/Ironmon-Tracker#270]
When clicking on a Pokemon's icon to view more information about that Pokemon, only its type-weaknesses are shown. Ideally this screen should also show resistances and any immunities. This has been a feature enhancement requested by a few people already.

#### Current Pokemon info look-up screen
![image](https://user-images.githubusercontent.com/4258818/196055300-a4444859-5bbc-4fe0-be13-bc34417729e4.png)

#### Notes on implementation
- I suspect we can remove the extra filler information here, such as **BST**, **Weight**, and **Evolution** details. This information is already available on the previous main Tracker screen. One case for keeping the Evolution is when you want to look up a Pokemon that isn't currently on screen, such as trying to remember how a Clamperl evolves.
- The **icon** of the Pokemon and its current **types** must remain on this info lookup and should not be removed
- It's important that **weaknesses** and **levelup move** information remains on this first screen, as it should be easily accessible from a single click. It's also important that the **notes** section is available on this first screen. In other words, when a user clicks on the Pokemon icon to learn more about a Pokemon, they shouldn't then have to click on something else to see any of this information; it should have already been revealed to them.

**Comment by Fellshadow** [comment]
what about as a rough idea for an initial implementation, arrows to cycle weaknesses/resists/immunities? Arrows either here or on either side of the text like the route encounter areas
![image](https://user-images.githubusercontent.com/106463662/196062007-ca9ac019-cd8b-42ad-ad38-83a78e583291.png)
![image](https://user-images.githubusercontent.com/106463662/196062316-15c70be3-eba9-4c49-92d4-bc452742fb34.png)


To chime in on the filler info, i kinda like being able to look up the BST within this menu occasionally (rather than looking it up on an external site), not dying to keep it there but i think some people probably like being able to look it up in the tracker. Not sure how useful the weight info is though

**Comment by jtigues** [comment]
Noting also that the highest number of resistances is water/steel at 12 in gen 3. You can only get that through randomized typing though.

**Comment by UTDZac** [comment]
Leaving a note that the data is will be available after the mGBA branch merge in (at some point in the future). Will still have the question on how best to show it all on the pokemon display page.

![image](https://cdn.discordapp.com/attachments/989295121507971123/1047469849745567814/image.png)

**Comment by UTDZac** [comment]
Resolved as of Tracker 7.3.0 release.
