### ISSUE TITLE
[Bug]: Tracker shows no text when launching (Wine + MacOS)

### ISSUE THREAD

**Issue by LukasSeemann** [besteon/Ironmon-Tracker#441]
### Describe the bug

Although I didn't find any tutorial on how to run Bizhawk + Ironmon Tracker on MacOS, I managed to get Bizhawk 2.9 up and running with Wine 8.0.1 on Sonoma 14.1.1 .
The patched ROM also can be loaded and played, but when I start the Lua script for the Ironmon Tracker I only see the startup Pokemon but no text. I can click on some buttons, but there is no text displayed anywhere (I can even change the startup Pokemon and its tracks Pokemon when playing the game).
There are no errors in the Lua console. 

Any ideas how to fix this? Might be a problem with Wine and Lua not working together properly.

### Steps to Reproduce

1. Start up Bizhawk 2.9 with Wine Crossover 8.0.1
2. Open Patched ROM of Emerald Nat Dex
3. Tools --> Lua Console --> Open Script --> Ironmon-Tracker.lua
4. See attached image

### What tracker version are you using?

v8.4.1

### What operating system are you using?

MacOS (Sonoma 14.1.1)

### What emulator(s) are you seeing the problem on?

Bizhawk 2.9

### Relevant log output

```shell
Lua log output:
Loading NatDex v1.0.2 Tracker for Bizhawk (Gen 3)
Ironmon Tracker v8.4.1 successfully loaded
> Tracker Notes: Loaded from last play session.

Wine version:
wine --version
wine-8.0.1 (CrossOver FOSS 23.0.1)
```

### Additional Information

<img width="993" alt="Bildschirmfoto 2023-12-14 um 16 30 00" src="https://github.com/besteon/Ironmon-Tracker/assets/19647820/6b1aceb3-b5fb-4999-93f2-4d646e880919">

**Comment by Fellshadow** [comment]
1. Have you tested with a regular ironmon rom and the regular gen 3 tracker to rule out if this is potentially somehow an issue with the nat dex custom tracker and not the base gen 3 tracker?
2. I don't have much knowledge of Wine + MacOS but on linux at least we have a [note](https://github.com/besteon/Ironmon-Tracker/wiki/Installation-Guide#notes-for-linux-users) for people to download and install the [Franklin Gothic Medium font](https://fontsgeek.com/fonts/Franklin-Gothic-Medium-Regular) as that's the font the tracker uses. Perhaps check if you have this font installed / try installing it and seeing if that fixes your issue

**Comment by LukasSeemann** [comment]
Thank you for your help. 
1. I just tried it with regular Firered Ironmon and the regular gen 3 tracker, it shows exactly the same screen. So it's not a problem of the nat dex custom tracker.
2. Thank you for that hint. I just installed that font on my Mac and at least I can see the text now. But the text is quite blurry and also all the icons (for settings, notes, back button etc.) are missing but clickable. Same behavior for normal Ironmon and regular gen 3 tracker. Any idea how to fix that?

<img width="779" alt="Bildschirmfoto 2023-12-14 um 19 16 17" src="https://github.com/besteon/Ironmon-Tracker/assets/19647820/894eccc7-0c97-4b78-aec1-696846b06d8d">

**Comment by Fellshadow** [comment]
> But the text is quite blurry and also all the icons (for settings, notes, back button etc.) are missing but clickable. Same behavior for normal Ironmon and regular gen 3 tracker. Any idea how to fix that?

Hm, i'm not sure on this one although I *have* seen one or two people have this issue when they set it up on the steam deck using Wine so I feel like Wine is maybe the issue here?

Is it the Windows or the Linux download of bizhawk that you're using here? From what I remember seeing of people setting it up on the steam deck they used the Linux version *but* that feels weird to me since Wine is a compatibility layer to run Windows applications. I don't have a mac or a steam deck to test myself but I do wonder if Windows vs Linux downloads of bizhawk would behave differently when ran with Wine

**Comment by LukasSeemann** [comment]
> Is it the Windows or the Linux download of bizhawk that you're using here? 

I am using the Windows version of Bizhawk. The Linux version is not working with Wine for me, there is an error with dll files.
My experience so far with Wine and Bizhawk: Performance is not good. You can only play the game on view 2x, larger resolution causes a major frame drop. ROM reload shortcut is also not working properly. So there are some issues ...

**Comment by Fellshadow** [comment]
ah ok, well it seems like it's an issue between Wine / Bizhawk rather than the tracker itself so i'll mark this issue as such.

If you want an alternative option to try out, i've seen some folks get things running on MacOS via Parallels Desktop (though nobody's really laid out any specific steps or anything for that as far as i'm aware, and how well it works I have no idea), if you do try that and you get issues with file permissions or the tracker accessing its files then [see here](https://github.com/besteon/Ironmon-Tracker/wiki/Installation-Guide#note-for-parallels-on-mac-os-users).

**Comment by UTDZac** [comment]
Closing this issue as "Won't fix", given it's related to external factors. If this isn't the case, let me know and we can investigate further how to resolve this.
