### ISSUE TITLE
[Bug]: Incorrect ability name in English.lua

### ISSUE THREAD

**Issue by Piomale** [besteon/Ironmon-Tracker#456]
### Describe the bug

In the file English.lua , there is a typo in the ability "Bubble Beam." It is written as "BubbleBeam" (without a space).

Due to this missing space, the ability can't be translated, and it's not possible to click on it to view details.``

### Steps to Reproduce

- Click on the ability BubbleBeam in the log,
- nothing happen (and not translated)
![image](https://github.com/besteon/Ironmon-Tracker/assets/88030270/c507e7c4-0e63-4455-8bda-fca0c375d9ab)

### What tracker version are you using?

v8.5.1

### What operating system are you using?

Windows 11

### What emulator(s) are you seeing the problem on?

Bizhawk 2.9

**Comment by Fellshadow** [comment]
Bit confused on the overall issue, "BubbleBeam" without a space is how it is spelled in the english versions of the games prior to X & Y so the lack of space is the correct version here.

I just loaded up a rom myself and "BubbleBeam" shows without a space in the name and clicks fine onto the move info both on the main screen and in the log viewer.

Perhaps you can share a bit more info on your setup here, when you're talking about translations which language setting are you using and are you playing a non-english rom?

Also have you made any customizations to the rom at all, such as changing pokemon and/or move names?
If you've changed the names of moves in the rom then that might be what's causing this issue here potentially

**Comment by Zach0Dac** [comment]
The language is french, if it helps.

**Comment by Piomale** [comment]
I just tested it, and you're right. In the base game, it should indeed be "BubbleBeam."

It seems that the error originates from the game generation by NatDexExtension, which renames the ability's name.
