### ISSUE TITLE
Gen 4 Support

### ISSUE THREAD

**Issue by Brian0255** [besteon/Ironmon-Tracker#70]
So the past few days I've been working a lot on figuring out how to add support for Gen 4 games. So far I've managed to find memory  for your primary pokemon, primary mon in battle, primary enemy mon in battle, etc. I've also managed to decrypt it and display it on the tracker correctly:

![image](https://user-images.githubusercontent.com/61294586/171984574-d5c65586-e8b1-4a8a-b201-5be0e29ff30c.png)

The main problem right now is that I have no idea where flags are for things like poison, entering a battle, ending a battle, etc. (or if they even exist). 

The only thing I can think of right now is to just update the tracker to check memory every 30 frames or something, which is obviously much less ideal than using the event based system that gen 3 has right now. However, I do think this could be viable if the calls to memory are put to an absolute minimum(which I have managed to do in the decryption.)  I do know that the memory for the active enemy mon is zeroed out when battle is not present, so I'm not sure if that could help somehow.

Anyways, I would be curious to hear anyone's thoughts on this or any ideas about how I could go about doing this

**Comment by bdjeffyp** [comment]
I'm happy to see this work! Thanks so much for getting this Gen 4 work started!

Memory values are tricky to get. For Gen 3, a lot of the work was already done: https://github.com/pret/pokefirered/tree/symbols.

These symbols listed all of the memory addresses and their associated variable or function. Unfortunately, Gen 4 does not have these files yet, because decompilation work is still ongoing. One avenue I suggested in #62 was the [RetroAchievements](https://retroachievements.org/codenotes.php?g=7212) project's code notes the achievement developers have put together for these games. They put in a lot of work on the Gen 4 games to get achievements running and may have documented just what we need. As the disclaimer suggests at the top, the values may not be accurate because of the way RetroAchievements maps memory for the achievement system, but it's worth a shot. At the bottom of their code notes for HGSS, they found a 16-bit value at 0x244eaa for battle status. Perhaps that is a start.

Ultimately, we are going to need to figure out these memory addresses. While memory reading is slow, it is also the source of truth. I am of the mindset that it is better to take the time to find these memory addresses, either with resources already available, or by searching memory ourselves. Making use of emulators' ability to search memory for value changes can help us identify these ideal addresses as well.

**Comment by Brian0255** [comment]
Oh wow, nice find! That should help a ton for this
