### ISSUE TITLE
Enemy Pokémon showed all moves/stats!

### ISSUE THREAD

**Issue by bdjeffyp** [besteon/Ironmon-Tracker#75]
Clip from Tso15 showing this occurring...
https://clips.twitch.tv/SteamyFlirtySandstormTF2John-gGYhi_luFfflOvQL

Great catch finding this. Let's see if we can repro and pinpoint the conditions that caused it. It almost seems like the logic thought that the Sealeo was the player's Pokémon for a moment.

**Comment by Fellshadow** [comment]
I've been trying to have a look and see if I can notice anything or pinpoint anything down but i'm not sure what's going on. I'll put my current thoughts out here though in case any of it helps or invokes any ideas (apologies for upcoming wordyness lmao):

It's a seemingly difficult scenario to accurately reproduce, without knowing what tracker settings were enabled and what the user inputs were at the time. All we know from just the clip alone is that it occurred at the end of a turn during the burn animation in the lab fight. The lab fight to note does have some different battle coding causing some of the weirdness we know about like player moves bypassing accuracy, if this could be a factor. If it were possible to get the log file for this seed we would at least be able to reproduce the exact same seed using the randomisation seed and settings string in the log file.

It does seem very likely that the tracker logic had thought the sealeo was the player's mon for that moment, as the ability is showing as magma armor (which the rattata had) and the speed increases that were there normally from agility were gone in the moment, though why only these two bits of information would be retained from rattata and not updated to pull sealeo's values like the rest of the tracker fields I do not know.

If this is the case (and I could of course be on the wrong track entirely here), then I think most likely the Drawing.DrawTracker function got called with the incorrect monIsEnemy value, which would only happen if the Tracker.Data.selectedPlayer value was incorrect. The only places where this value gets changed is when CYCLE_VIEW gets pressed, the tracker is auto-swapping to the enemy when AUTO_SWAP_TO_ENEMY is enabled, and at the end of battle.

The AUTO_SWAP_TO_ENEMY setting would only change the selectedPokemon value when an enemy pokemon is sent out or uses a move, neither of which occur here so we can rule that out. It is also not at the end of a battle, so that leaves just CYCLE_VIEW. I can hear a button being mashed immediately before the occurrence of the bug, though impossible to tell which button it is so can't say for sure whether it's CYCLE_VIEW or not.

Would it maybe be possible that somewhere in this mashing (if it is indeed the CYCLE_VIEW button), the values are changing while the tracker is still in the process of redrawing and the redraw happens to occur in the middle of values being changed such that it reads values that haven't been correctly updated yet? Wouldn't be able to test that theory in full without reproducing the bug though.

**Comment by bdjeffyp** [comment]
Thanks for the thoughts! They are definitely encouraged and helpful.

This is the only instance that I have ever heard/seen of this sort of thing happening, thankfully. We may not be able to repro this until we can get more instances of this happening...

**Comment by Fellshadow** [comment]
Not sure if this happened to get fixed in a later tracker version or not but just to note here, fuzzyness just had this bug on tracker v0.2.2 - https://clips.twitch.tv/ArtisticDependableCakeCopyThis-oaqhG8RHW_oFyplV

they're now trying out the preliminary v0.5.0 build from zac, so may let us know if there's any issues from using that version

**Comment by UTDZac** [comment]
Thanks for the info on which version this is at least happening in. I agree it's unlikely (near impossible) for this info to be revealed with the 0.5.0 code rework and the `Tracker.Data.isViewingOwn` flag.
