### ISSUE TITLE
feature request: show effort values (EVs)

### ISSUE THREAD

**Issue by ETR-BTF** [besteon/Ironmon-Tracker#76]
I think I have the know-how to code this myself, but I thought I'd ask if this has a chance of getting accepted before I put in the _effort_ (hehe).

Just like a Pokémon's weight this is info you can just look up, so I don't think it'd be giving the player too much info. 

The tracker could also keep track of how many EVs your Pokémon have accumulated. While this technically doesn't give the player info they couldn't otherwise have, I understand that it could be considered as helping the player too much. 

Space on the tracker could be an issue. 

I'm looking forward to hearing feedback. :)

**Comment by ETR-BTF** [comment]
EXP yield (or base EXP) might be nice on wild encounters too for regular/ultimate. Helps decide which kill to go for.

**Comment by bdjeffyp** [comment]
EVs and IVs are meant to be hidden and are thus not allowed to be revealed via the tracker. Information the tracker shows is to be only from what can reasonably gained in-game. EVs are not measurable in Gen 3 (the values themselves aren't even shown on the radars in Gen 6 and later). Experience yield is also something that isn't necessarily revealed in-game, rather depending on player knowledge that a rarer or more evolved Pokémon will yield more experience.

Weight is known because of the Pokédex. I was hesitant on even adding the weight calculations until I got buy-off from Pie on it, and he even initially said "no" when I brought it up to him. So my stance is pretty conservative when it comes to adding things like this to the tracker.

I do appreciate that you asked first and even volunteered to implement something like this. Projects like this become better when people with a wide range of ideas come together. I'm sorry that this one is just not feasible, but I hope that you'd like to further contribute in other ways or provide other ideas that may be missing/lacking in the tracker. The best thing to keep in mind is if the information is already presented in the game in some form. If it is, then we are more likely to incorporated it into the tracker as long as there is space for it.

**Comment by ETR-BTF** [comment]
I understand. You have to draw the line somewhere and information that is already available in-game (e.g. in the Pokédex) is a well-defined line, which I can appreciate. If I have other ideas I'll be sure to open another issue!
