### ISSUE TITLE
Transforming into a Pokemon gives you info on their ability that you shouldn't have

### ISSUE THREAD

**Issue by UTDZac** [besteon/Ironmon-Tracker#87]
This is a bug. Using transform causes some issues with the tracker, one major and one minor, detailed below.

### The major issue
Immediately after using Transform, your Pokemon's ability on the tracker changes to the targeted Pokemon's ability, giving you information you shouldn't be able to access (you can't see it by viewing the Pokemon's summary in-game). Looking at the reference image below, Poliwhirl has the ability Shed Skin, while Charmeleon has Rough Skin.

Is this similar to #30 ?

### The minor issue
After transformation, the tracker continues to show your original Pokemon's moveset and stats. I image not revealing the stats is a good thing. The moveset not reflecting the Pokemon it became is only a small concern; or maybe not one at all. It's not really important to track this data necessarily. However, many people find it useful to know what move is effective against the opposing Pokemon. There may be other reasons to temporarily see the transformed moves show in the tracker.

### Reference image
![image](https://user-images.githubusercontent.com/4258818/174476889-75739e30-f1cc-4c0b-a2e3-1943c2d20bb1.png)

**Comment by Fellshadow** [comment]
In regards to the ability, i'm pretty sure the cause is the same as both #30 and #13 showing the opponent's abilities

Since the ability is being read from sBattlerAbilities, which is the in-battle ability data, my guess is when the player's ability is changed due to transform / skill swap / trace and probably similar things like role play the game changes the ability ID stored in sBattlerAbilities to the ability that was copied/swapped over to the player

So if this is the case, then the most optimal solution would be to find a better memory address that permanently stores the pokemon's original ability, ideally one that also stores the ability outside of battle too which would also resolve #1. Whether this exists or not I don't know

I've tried to have a look for this but i don't know much regarding pulling data from game memory or what memory addresses to try so not found anything too promising yet but the decomp code has a big list of them if anyone else wants to try looking (for FRLG they're here - https://github.com/pret/pokefirered/tree/symbols)

**Comment by UTDZac** [comment]
That's a good point. I suppose one of the cleanest ways to handle this is to treat being transformed as being in a special state, a state such that the game doesn't reveal data on the tracker about yourself. Similar to how we have being in a state of "Must Check Summary" to hide data from the player.

**Comment by Fellshadow** [comment]
yeah possibly, there is a boolean variable I introduced (`Program.transformedPokemon.isTransformed`) to fix the issue where the tracker will overwrite a pokemon's tracked moves with your moves if they transformed (PR #61).

This could maybe be used to also hide copied abilities for the player when the player is transformed. Wouldn't need to worry about a scenario where both pokemon are transformed since in gen 3 transform fails when used on a transformed pokemon, so only 1 can be transformed at a time.
